// Generated by src/build.ts — do not edit.
// Inlines dist/public as base64 so both the js bundle and native
// binaries ship the frontend as a single file.
//
// The committed version is an empty stub; dev falls through to disk-based
// serving via @elysiajs/static. `bun run build` overwrites this file with
// the real manifest, then restores the stub once the artifacts are emitted.

export type EmbeddedAsset = {
  path: string;
  contentType: string;
  base64: string;
};

export const embeddedAssets: EmbeddedAsset[] = [];
