// Generated by src/build.ts — do not edit.
// Imports every file in dist/public as an embedded asset so native
// binaries ship with the frontend baked in.

import _0 from "../../dist/public/index.html" with { type: "file" };
import _1 from "../../dist/public/chunk-yrs9gq0q.js" with { type: "file" };
import _2 from "../../dist/public/chunk-yrs9gq0q.js.map" with { type: "file" };
import _3 from "../../dist/public/chunk-2fbnvtd2.css" with { type: "file" };

export const embeddedAssetPaths = [
  ["index.html", _0] as const,
  ["chunk-yrs9gq0q.js", _1] as const,
  ["chunk-yrs9gq0q.js.map", _2] as const,
  ["chunk-2fbnvtd2.css", _3] as const,
];
