import type { OpenAIFreeDiscovery } from "@core/vendors/shared/openai-free-provider";
import { t } from "@server/i18n";
import { consola } from "consola";

// Vercel AI Gateway (ai-gateway.vercel.sh/v1) - $5 recurring free credit (card on file, hard-
// capped per-key so it can never bill beyond the credit). Legit multi-provider gateway: each
// vendor/slug routes to the REAL upstream (anthropic/openai/google/xai/deepseek/...), so no fake-
// model risk. Free tier RATE-LIMITS (429) rather than blocks; acceptRateLimited + new-api failover
// absorb it. Only 4 grok-4.20-multi-agent/non-reasoning ids are hard-403 (excluded). Full slug is
// forwarded (new-api OpenAI adaptor handles vendor/ prefix); bare-name strips it for publish,
// modelMapping collapses variants. Hardcoded so a catalog change can't leak an untested/403 id.
const MODELS = [
  "anthropic/claude-3.5-haiku",
  "anthropic/claude-3-haiku",
  "anthropic/claude-fable-5",
  "anthropic/claude-haiku-4.5",
  "anthropic/claude-opus-4",
  "anthropic/claude-opus-4.1",
  "anthropic/claude-opus-4.5",
  "anthropic/claude-opus-4.6",
  "anthropic/claude-opus-4.7",
  "anthropic/claude-opus-4.8",
  "anthropic/claude-sonnet-4",
  "anthropic/claude-sonnet-4.5",
  "anthropic/claude-sonnet-4.6",
  "anthropic/claude-sonnet-5",
  "deepseek/deepseek-r1",
  "deepseek/deepseek-v3",
  "deepseek/deepseek-v3.1",
  "deepseek/deepseek-v3.1-terminus",
  "deepseek/deepseek-v3.2",
  "deepseek/deepseek-v3.2-thinking",
  "deepseek/deepseek-v4-flash",
  "deepseek/deepseek-v4-pro",
  "google/gemini-2.5-flash",
  "google/gemini-2.5-flash-lite",
  "google/gemini-2.5-pro",
  "google/gemini-3.1-flash-lite",
  "google/gemini-3.1-flash-lite-preview",
  "google/gemini-3.1-pro-preview",
  "google/gemini-3.5-flash",
  "google/gemini-3-flash",
  "google/gemini-3-pro-preview",
  "google/gemini-omni-flash-preview",
  "google/gemma-4-26b-a4b-it",
  "google/gemma-4-31b-it",
  "minimax/minimax-m2",
  "minimax/minimax-m2.1",
  "minimax/minimax-m2.1-lightning",
  "minimax/minimax-m2.5",
  "minimax/minimax-m2.5-highspeed",
  "minimax/minimax-m2.7",
  "minimax/minimax-m2.7-highspeed",
  "minimax/minimax-m3",
  "moonshotai/kimi-k2",
  "moonshotai/kimi-k2.5",
  "moonshotai/kimi-k2.6",
  "moonshotai/kimi-k2.7-code",
  "moonshotai/kimi-k2.7-code-highspeed",
  "moonshotai/kimi-k2-thinking",
  "openai/gpt-4.1",
  "openai/gpt-4.1-mini",
  "openai/gpt-4.1-nano",
  "openai/gpt-4o",
  "openai/gpt-4o-mini",
  "openai/gpt-4o-mini-search-preview",
  "openai/gpt-4-turbo",
  "openai/gpt-5",
  "openai/gpt-5.1-codex",
  "openai/gpt-5.1-codex-max",
  "openai/gpt-5.1-codex-mini",
  "openai/gpt-5.1-instant",
  "openai/gpt-5.1-thinking",
  "openai/gpt-5.2",
  "openai/gpt-5.2-chat",
  "openai/gpt-5.2-codex",
  "openai/gpt-5.2-pro",
  "openai/gpt-5.3-chat",
  "openai/gpt-5.3-codex",
  "openai/gpt-5.4",
  "openai/gpt-5.4-mini",
  "openai/gpt-5.4-nano",
  "openai/gpt-5.4-pro",
  "openai/gpt-5.5",
  "openai/gpt-5.5-pro",
  "openai/gpt-5.6-luna",
  "openai/gpt-5.6-sol",
  "openai/gpt-5.6-terra",
  "openai/gpt-5-chat",
  "openai/gpt-5-codex",
  "openai/gpt-5-mini",
  "openai/gpt-5-nano",
  "openai/gpt-5-pro",
  "openai/gpt-oss-120b",
  "openai/gpt-oss-20b",
  "openai/gpt-oss-safeguard-20b",
  "openai/o1",
  "openai/o3",
  "openai/o3-mini",
  "openai/o3-pro",
  "openai/o4-mini",
  "xai/grok-4.1-fast-non-reasoning",
  "xai/grok-4.1-fast-reasoning",
  "xai/grok-4.20-reasoning",
  "xai/grok-4.20-reasoning-beta",
  "xai/grok-4.3",
  "xai/grok-4.5",
  "zai/glm-4.5",
  "zai/glm-4.5-air",
  "zai/glm-4.5v",
  "zai/glm-4.6",
  "zai/glm-4.6v",
  "zai/glm-4.6v-flash",
  "zai/glm-4.7",
  "zai/glm-4.7-flash",
  "zai/glm-4.7-flashx",
  "zai/glm-5",
  "zai/glm-5.1",
  "zai/glm-5.2",
  "zai/glm-5.2-fast",
  "zai/glm-5-turbo",
  "zai/glm-5v-turbo",
];

export async function discoverVercelModels(
  _baseUrl: string,
  _apiKey: string,
): Promise<OpenAIFreeDiscovery> {
  consola.info(
    t("CORE.PROVIDER.DISCOVERY_FETCH", {
      label: "Vercel AI Gateway",
      url: "(free-tier frontier chat set)",
    }),
  );
  return { models: MODELS, maxOutputByModel: new Map() };
}
