#!/usr/bin/env bun
/**
 * Release build. Produces:
 *   dist/public/           — frontend (tailwind compiled); kept for reference
 *   dist/new-api-sync.js   — portable js bundle, frontend inlined as base64
 *   dist/new-api-sync-<t>  — native binary per target, frontend inlined
 *
 * Both artifact types are single-file. The frontend assets are inlined into
 * the generated `src/server/embedded-assets.ts` manifest as base64 strings,
 * so the js bundle and the native binaries pick them up uniformly.
 */
import tailwindPlugin from "bun-plugin-tailwind";
import { error, log } from "node:console";
import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { rm } from "node:fs/promises";
import { extname, relative } from "node:path";

const DIST = "dist";
const ENTRY = "src/cli/index.ts";
const ASSETS_MANIFEST = "src/server/embedded-assets.ts";
const TARGETS = [
  "bun-linux-x64",
  "bun-linux-arm64",
  "bun-darwin-x64",
  "bun-darwin-arm64",
  "bun-windows-x64",
  "bun-windows-arm64",
];

// Minimal content-type lookup; anything not here falls back to octet-stream
// at serve time.
const CONTENT_TYPES: Record<string, string> = {
  ".html": "text/html; charset=utf-8",
  ".css": "text/css; charset=utf-8",
  ".js": "application/javascript; charset=utf-8",
  ".map": "application/json; charset=utf-8",
  ".json": "application/json; charset=utf-8",
  ".svg": "image/svg+xml",
  ".png": "image/png",
  ".jpg": "image/jpeg",
  ".jpeg": "image/jpeg",
  ".gif": "image/gif",
  ".ico": "image/x-icon",
  ".woff": "font/woff",
  ".woff2": "font/woff2",
};

const binaryPath = (t: string) =>
  `${DIST}/new-api-sync-${t.replace(/^bun-/, "")}${t.includes("windows") ? ".exe" : ""}`;

const run = async (cmd: string[]) => {
  const code = await Bun.spawn({ cmd, stdout: "inherit", stderr: "inherit" })
    .exited;
  if (code !== 0) process.exit(code);
};

const build = async (options: Parameters<typeof Bun.build>[0]) => {
  const result = await Bun.build(options);
  if (result.success) return;
  error(result.logs);
  process.exit(1);
};

// Walk dist/public recursively, returning paths relative to dist/public.
const listAssets = (dir: string, base = dir): string[] => {
  const out: string[] = [];
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    const full = `${dir}/${entry.name}`;
    if (entry.isDirectory()) out.push(...listAssets(full, base));
    else out.push(relative(base, full));
  }
  return out;
};

// Generate a TS module that inlines every file in dist/public as a base64
// string + content type. Both the js bundle and native binaries import this
// and serve from memory — no disk reads, no separate public/ dir required.
const writeAssetManifest = (assets: string[]) => {
  const lines = [
    "// Generated by src/build.ts — do not edit.",
    "// Inlines dist/public as base64 so both the js bundle and native",
    "// binaries ship the frontend as a single file.",
    "",
    "export type EmbeddedAsset = {",
    "  path: string;",
    "  contentType: string;",
    "  base64: string;",
    "};",
    "",
    "export const embeddedAssets: EmbeddedAsset[] = [",
  ];
  for (const asset of assets) {
    const full = `${DIST}/public/${asset}`;
    const base64 = readFileSync(full).toString("base64");
    const contentType =
      CONTENT_TYPES[extname(asset).toLowerCase()] ?? "application/octet-stream";
    lines.push("  {");
    lines.push(`    path: ${JSON.stringify(asset)},`);
    lines.push(`    contentType: ${JSON.stringify(contentType)},`);
    lines.push(`    base64: ${JSON.stringify(base64)},`);
    lines.push("  },");
  }
  lines.push("];");
  lines.push("");
  writeFileSync(ASSETS_MANIFEST, lines.join("\n"));
};

await rm(DIST, { recursive: true, force: true });

log("• typecheck");
await run(["bun", "run", "tsc", "--noEmit"]);

log("• frontend");
await build({
  entrypoints: ["src/web/public/index.html"],
  outdir: `${DIST}/public`,
  target: "browser",
  minify: true,
  // Sourcemaps are skipped intentionally: they'd bloat the js bundle
  // (2+ MB base64-encoded) for no user-facing benefit in a shipped build.
  plugins: [tailwindPlugin],
});

log("• asset manifest");
const assets = listAssets(`${DIST}/public`);
writeAssetManifest(assets);

log("• js bundle");
await build({
  entrypoints: [ENTRY],
  outdir: DIST,
  naming: "new-api-sync.js",
  target: "bun",
  format: "esm",
  minify: true,
  packages: "bundle",
});

for (const target of TARGETS) {
  log(`• binary ${target}`);
  await run([
    "bun",
    "build",
    "--compile",
    `--target=${target}`,
    "--minify",
    ENTRY,
    `--outfile=${binaryPath(target)}`,
  ]);
}

// Restore the empty stub so `bun dev` keeps falling through to disk-based
// serving. The populated manifest is already baked into the js bundle and
// native binaries above; leaving it on disk would silently flip dev mode
// into prod mode on the next `bun dev`.
log("• reset manifest stub");
writeFileSync(
  ASSETS_MANIFEST,
  `// Generated by src/build.ts — do not edit.
// Inlines dist/public as base64 so both the js bundle and native
// binaries ship the frontend as a single file.
//
// The committed version is an empty stub; dev falls through to disk-based
// serving via @elysiajs/static. \`bun run build\` overwrites this file with
// the real manifest, then restores the stub once the artifacts are emitted.

export type EmbeddedAsset = {
  path: string;
  contentType: string;
  base64: string;
};

export const embeddedAssets: EmbeddedAsset[] = [];
`,
);

log("✓ done");
