#!/usr/bin/env bun
/**
 * Release build. Produces:
 *   dist/public/           — frontend (tailwind compiled, stable filenames)
 *   dist/new-api-sync.js   — portable js bundle (deps inlined, reads public/ from disk)
 *   dist/new-api-sync-<t>  — native binary per target (public/ embedded)
 *
 * Native binaries embed dist/public/ directly using Bun's `with { type: "file" }`
 * attribute, so they're single-file — nothing to extract alongside.
 */
import { readdirSync, writeFileSync } from "node:fs";
import { rm } from "node:fs/promises";
import { relative, resolve } from "node:path";
import tailwindPlugin from "bun-plugin-tailwind";

const DIST = "dist";
const ENTRY = "src/cli/index.ts";
const ASSETS_MANIFEST = "src/server/embedded-assets.ts";
const TARGETS = [
  "bun-linux-x64",
  "bun-linux-arm64",
  "bun-darwin-x64",
  "bun-darwin-arm64",
  "bun-windows-x64",
  "bun-windows-arm64",
];

const binaryPath = (t: string) =>
  `${DIST}/new-api-sync-${t.replace(/^bun-/, "")}${t.includes("windows") ? ".exe" : ""}`;

const run = async (cmd: string[]) => {
  const code = await Bun.spawn({ cmd, stdout: "inherit", stderr: "inherit" })
    .exited;
  if (code !== 0) process.exit(code);
};

const build = async (options: Parameters<typeof Bun.build>[0]) => {
  const result = await Bun.build(options);
  if (result.success) return;
  console.error(result.logs);
  process.exit(1);
};

// Walk dist/public recursively, returning paths relative to dist/public.
const listAssets = (dir: string, base = dir): string[] => {
  const out: string[] = [];
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    const full = `${dir}/${entry.name}`;
    if (entry.isDirectory()) out.push(...listAssets(full, base));
    else out.push(relative(base, full));
  }
  return out;
};

// Generate a TS module that imports every file in dist/public as an embedded
// asset. The imports use `with { type: "file" }` so Bun's --compile embeds the
// file contents into the binary. Paths are relative to this file's location.
const writeAssetManifest = (assets: string[]) => {
  const manifestDir = resolve(ASSETS_MANIFEST, "..");
  const lines = [
    "// Generated by src/build.ts — do not edit.",
    "// Imports every file in dist/public as an embedded asset so native",
    "// binaries ship with the frontend baked in.",
    "",
  ];
  assets.forEach((asset, i) => {
    const fromManifest = relative(manifestDir, resolve(DIST, "public", asset));
    lines.push(`import _${i} from "${fromManifest}" with { type: "file" };`);
  });
  lines.push("");
  lines.push("export const embeddedAssetPaths = [");
  assets.forEach((asset, i) => {
    lines.push(`  [${JSON.stringify(asset)}, _${i}] as const,`);
  });
  lines.push("];");
  lines.push("");
  writeFileSync(ASSETS_MANIFEST, lines.join("\n"));
};

await rm(DIST, { recursive: true, force: true });

console.log("• typecheck");
await run(["bun", "run", "tsc", "--noEmit"]);

console.log("• frontend");
await build({
  entrypoints: ["src/web/public/index.html"],
  outdir: `${DIST}/public`,
  target: "browser",
  minify: true,
  sourcemap: "linked",
  naming: { asset: "[name].[ext]" },
  plugins: [tailwindPlugin],
});

console.log("• asset manifest");
const assets = listAssets(`${DIST}/public`);
writeAssetManifest(assets);

console.log("• js bundle");
await build({
  entrypoints: [ENTRY],
  outdir: DIST,
  naming: "new-api-sync.js",
  target: "bun",
  format: "esm",
  minify: true,
  packages: "bundle",
});

for (const target of TARGETS) {
  console.log(`• binary ${target}`);
  await run([
    "bun",
    "build",
    "--compile",
    `--target=${target}`,
    "--minify",
    "--asset-naming=[name].[ext]",
    ENTRY,
    `--outfile=${binaryPath(target)}`,
  ]);
}

console.log("✓ done");
